verbosity = 0
hostname = 'hostname'
pagerduty_routing_key = 'routing_key'

[auto_configure]
exception_trace = true
fatal_signals = true
klog_include_timestamp = true

[analytics]
mode = 'Passthrough'
justification = 'Summary'
collection_timeout_seconds = 10
max_event_count = 20
event_lifetime_seconds = 30
event_drop_count = 5

[monitor]
gobble_old_events = false

[console]
format = 'Text'

[polycorder]
auth_key = 'AuthKeyFromPolyverseAccountManager'
node_id = 'UsefulNodeIdentifierToGroupEvents'
flush_event_count = 10
flush_timeout_seconds = 10

[syslog]
format = 'Cef'
destination = 'Udp'
path = '# only applicable to unix - path to unix socket to connect to syslog (i.e. /dev/log or /var/run/syslog)'
server = '# applicable to tcp and udp - the host:port to send syslog to (i.e. 127.0.0.1:601 or 127.0.0.1:514)'
local = '# only applicable to udp - the host:port to bind sender to (i.e. 127.0.0.1:0)'

[logfile]
format = 'Cef'
filepath = '/test/path'
rotation_file_count = 1
rotation_file_max_size = 20
